openapi: 3.1.0
info: 
    title: Swagger pour le projet fil rouge
    version: 1.0.0
servers: 
    - url: http://localhost:5000
components: 
    securitySchemes: 
        bearerAuth: 
            type: http
            scheme: bearer
            bearerFormat: JWT
security: 
    - bearerAuth: []
paths: 
    /auth/register: 
        post: 
            tags: 
                - Auth
            summary: Créer un nouvel utilisateur
            requestBody: 
                required: true
                content: 
                    application/json: 
                        schema: 
                            type: object
                            properties: 
                                email:  
                                    type: string 
                                password:  
                                    type: string
            responses: 
                '201':  
                    description: Utilisateur créé avec succès
                '400':  
                    description: Requête invalide
    /auth/login: 
        post: 
            summary: Authentifier un utilisateur
            tags: 
                - Auth
            requestBody: 
                required: true
                content: 
                    'application/json': 
                        schema: 
                            type: object
                            properties: 
                                email:  
                                    type: string
                                password:  
                                    type: string
            responses: 
                '200': 
                    description: Authentification réussie
                '401': 
                    description: Utilisateur introuvable ou mot de passe incorrect

    /contacts: 
        get: 
            summary: Récupérer les contacts de l'utilisateur
            tags: 
                - Contacts
            security: 
                - bearerAuth: [] 
            responses: 
                '200': 
                    description: Liste des contacts récupérée avec succès
                '401': 
                    description: Non autorisé 
        post: 
            summary: Créer un nouveau contact
            tags: 
                - Contacts
            security: 
                - bearerAuth: [] 
            requestBody: 
                required: true
                content: 
                    application/json: 
                        schema: 
                            type: object
                            properties: 
                                firstName:  
                                    type: string 
                                lastName:  
                                    type: string 
                                phone:  
                                    type: string 
                            required: ['firstName', 'lastName', 'phone']
            responses: 
                '201': 
                    description: Contact créé avec succès
                '400': 
                    description: Requête invalide
    /contacts/{id}: 
        patch: 
            summary: Mettre à jour un contact
            tags: 
                - Contacts
            security: 
                - bearerAuth: [] 
            parameters: 
                - name: id 
                  in: path 
                  required: true 
                  schema: 
                  type: string 
            requestBody: 
                required: true
                content: 
                    application/json: 
                        schema: 
                            type: object
                            properties: 
                                firstName: 
                                    type: string
                                lastName: 
                                    type: string 
                                phone: 
                                    type: string 
            responses: 
                '200': 
                    description: Contact mis à jour avec succès
                '404': 
                    description: Contact introuvable
        delete: 
            summary: Supprimer un contact
            tags: 
                - Contacts
            security: 
                - bearerAuth: []
            parameters: 
                - name: id 
                  in: path 
                  required: true 
                  schema: 
                  type: string 
            responses: 
                '200': 
                    description: Contact supprimé avec succès 
                '404': 
                    description: Contact introuvable